// <auto-generated />
using ChatBot.DataAccess.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatBot.DataAccess.MySql.Migrations
{
    [DbContext(typeof(ChatBotDbContext))]
    partial class ChatBotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ChatBot.DataAccess.MySql.Entities.ChatResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Intent")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("Intent");

                    b.ToTable("ChatResponses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Intent = "greeting",
                            ResponseMessage = "Hi, how can i help you?"
                        },
                        new
                        {
                            Id = 2L,
                            Intent = "greeting",
                            ResponseMessage = "Hello there, how can i help you?"
                        },
                        new
                        {
                            Id = 3L,
                            Intent = "greeting",
                            ResponseMessage = "Hey there, can i help you?"
                        },
                        new
                        {
                            Id = 4L,
                            Intent = "goodbye",
                            ResponseMessage = "Bye bye!"
                        },
                        new
                        {
                            Id = 5L,
                            Intent = "goodbye",
                            ResponseMessage = "It was nice talking to you, have a great day!"
                        },
                        new
                        {
                            Id = 6L,
                            Intent = "affirmative",
                            ResponseMessage = "Great!"
                        },
                        new
                        {
                            Id = 7L,
                            Intent = "affirmative",
                            ResponseMessage = "Perfect :)"
                        },
                        new
                        {
                            Id = 8L,
                            Intent = "negative",
                            ResponseMessage = "Alright, please let me know if I can help you with anything else!"
                        },
                        new
                        {
                            Id = 9L,
                            Intent = "thank you",
                            ResponseMessage = "It was a pleasure to be of help :)"
                        },
                        new
                        {
                            Id = 10L,
                            Intent = "are you a bot?",
                            ResponseMessage = "I'm an AI bot, and I'm here to help you with your questions."
                        },
                        new
                        {
                            Id = 11L,
                            Intent = "i want to speak with a human",
                            ResponseMessage = "Let me transfer you to the first available agent."
                        },
                        new
                        {
                            Id = 12L,
                            Intent = "login problems",
                            ResponseMessage = "Oh no! Please give me your email and I will fix it."
                        },
                        new
                        {
                            Id = 13L,
                            Intent = "i want to speak with a human",
                            ResponseMessage = "Let me transfer you to the first available agent."
                        },
                        new
                        {
                            Id = 14L,
                            Intent = "open or close account",
                            ResponseMessage = "Please follow these instructions \"LINK\" to open or close an account."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
